# This file is part of the Aurelia workspace.
# SPDX-FileCopyrightText: 2026 Zivatar Limited
# SPDX-License-Identifier: Apache-2.0

[workspace]
resolver = "2"
members = [
  "src/lib",
  "src/crates/data",
  "src/crates/ids",
  "src/crates/platform",
  "src/crates/logging",
  "src/crates/peering",
  "src/crates/resolver",
  "src/crates/xtask",
]
exclude = ["publish"]

[workspace.package]
edition = "2021"
rust-version = "1.74"
license = "Apache-2.0"
repository = "https://github.com/teeay/aurelia"
homepage = "https://teeay.dev/aurelia"
authors = ["teeay"]

[workspace.dependencies]
actix = "0.13"
anyhow = "1"
async-trait = "0.1"
asn1-rs = "0.6"
bitflags = "2"
bytes = "1"
caducus = "0.2.2"
cargo_metadata = "0.18"
clap = "4"
fs-err = "3"
futures = "0.3"
libc = "0.2"
rcgen = "0.12"
regex = "1"
ring = "0.17"
rustls-pki-types = "1"
serde = "1"
serde_json = "1"
tokio = "1"
tokio-rustls = { version = "0.26", default-features = false, features = ["logging", "tls12", "ring"] }
toml_edit = "0.22"
tracing = "0.1"
walkdir = "2"
x509-parser = "0.16"
zeroize = "1"

[workspace.metadata.aurelia-publish]
target_crate = "aurelia"
internal_crates = [
  { name = "aurelia-ids" },
  { name = "aurelia-data" },
  { name = "aurelia-platform" },
  { name = "aurelia-logging" },
  { name = "aurelia-peering" },
  { name = "aurelia-resolver" },
]
excluded_crates = ["xtask"]
