# This file is part of the Aurelia workspace.
# SPDX-FileCopyrightText: 2026 Zivatar Limited
# SPDX-License-Identifier: Apache-2.0

ARG AURELIA_E2E_BUILDER_BASE=aurelia-e2e-builder-base:local
ARG AURELIA_E2E_RUNTIME_BASE=aurelia-e2e-runtime-base:local

FROM ${AURELIA_E2E_BUILDER_BASE} AS builder
COPY --chown=appuser:appuser Cargo.toml Cargo.lock ./
COPY --chown=appuser:appuser src ./src
COPY --chown=appuser:appuser testing/peering/apps/peering-domus ./testing/peering/apps/peering-domus
RUN cargo build --release --manifest-path testing/peering/apps/peering-domus/Cargo.toml

FROM ${AURELIA_E2E_RUNTIME_BASE}
COPY --from=builder /workspace/testing/peering/apps/peering-domus/target/release/peering-domus /usr/local/bin/peering-domus
EXPOSE 5001
USER appuser
ENTRYPOINT ["peering-domus"]
